name: Supermercado Mass - Integración Continua (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-validation:
    name: Validar Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm de forma global
        run: npm install -g pnpm
      
      - name: Instalar Dependencias Frontend
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "Detectado pnpm-lock.yaml. Instalando con pnpm..."
            pnpm install
          else
            echo "No se encontro pnpm-lock.yaml. Instalando con npm..."
            npm install
          fi
      
      - name: Compilar Frontend (Build Test)
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm run build
          else
            npm run build
          fi

  backend-validation:
    name: Validar Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm de manera global
        run: npm install -g pnpm

      - name: Instalar Dependencias Backend
        run: |
          if [ -f "pnpm-lock.yaml"]; then
            echo "Detectado pnpm-lock.yaml. Instalando con pnpm..."
            pnpm install
          else
            echo "No se encontro pnpm-lock.yaml. Instalando con npm..."
            npm install
          fi

      - name: Verificar Sintaxis del Backend
        run: echo "Backend listo para integrarse"
